import React from "react";
import Head from "next/head";
import NavBar from "../nav-bar";
import Footer from "../footer";

interface IProps {
    children: React.ReactNode;
}

export default function DefaultLayout({ children }: IProps) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />

            <main>{children}</main>

            <Footer />
        </div>
    );
}
